Separated Darwin and Linux aliases
made separate aliases for Darwin and Linux and added functions lsp() to list all pictures and local-ip() which works different in both darwin and linux

diff --git a/config/bash/bash_aliases b/config/bash/bash_aliases
--- a/config/bash/bash_aliases
+++ b/config/bash/bash_aliases
@@ -1,40 +1,22 @@
-alias mocp="mocp -T black_orange"
-alias fums="sudo apt autoclean && sudo apt clean && sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y --purge && sudo snap refresh"
-alias up="sudo apt update && sudo apt upgrade -y && sudo apt autopurge -y"
-alias public-ip="python3 -c \"import requests; print(requests.get('https://api.ipify.org').text)\""
-alias install-date="/bin/ls -alct /|tail -1|awk '{print \$6, \$7, \$8}'"
+
+# COMMON ALIASES FOR BOTH LINUX AND DARWIN
+
 alias mp3="yt-dlp --extract-audio --audio-format mp3 --embed-thumbnail"
-alias open="xdg-open"
-alias cpufetch="cpufetch --color 239,90,45:210,200,200:0,0,0:100,200,45:0,200,200 -F"
-alias scrot="scrot -q 100"
-alias s="scrot -q 100"
-alias s1="scrot -q 100 -d 1"
-alias s3="scrot -q 100 -d 3"
-alias ld='find -maxdepth 1 -type d -exec basename {} \;'
-alias lA="/bin/ls -lA"
-alias local-ip="hostname -I | cut -d' ' -f1"
-alias shutdown="shutdown -P now"
-alias copy="xclip -i -selection clipboard"
-alias paste="xclip -o -selecton clipboard"
-alias wget="wget -c"
+alias public-ip="curl api.ipify.org || curl ifconfig.co || curl ifconfig.me || echo FAILED "
 alias gogh="bash -c  \"\$(wget -qO- https://git.io/vQgMr)\""
-
-# Aliases Copied from GARUDA
-
-# Replace cat with bat
-alias cat='batcat --style header --style rules --style snip --style changes --style header'
+alias wget="wget -c"
 
 # Replace ls with exa
-alias ls='exa -al --color=always --group-directories-first --icons' # preferred listing
-alias la='exa -a --color=always --group-directories-first --icons'  # all files and dirs
+alias la='exa -al --color=always --group-directories-first --icons' # preferred listing
+alias l='exa -a1 --color=always --group-directories-first --icons'  # all files and dirs
 alias ll='exa -l --color=always --group-directories-first --icons'  # long format
 alias lt='exa -aT --color=always --group-directories-first --icons' # tree listing
 alias l.="exa -a | egrep '^\.'"   
-alias l="exa -1"
+alias ls="exa -1"
+alias ld="\find . -maxdepth 1 -type d  | xargs basename "
+
 
 # Common use
-alias dir='dir --color=auto'
-alias vdir='vdir --color=auto'
 alias grep='grep --color=auto'
 alias fgrep='fgrep --color=auto'
 alias egrep='egrep --color=auto'
@@ -44,11 +26,90 @@ alias ....='cd ../../..'
 alias .....='cd ../../../..'
 alias ......='cd ../../../../..'
 
-alias get-chrome='wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
 alias gen-pass="LC_ALL=C tr -dc A-Za-z0-9_ < /dev/urandom | head -c 16 | xargs"
-
-alias show-wifi-password="nmcli device wifi show-password"
-
-alias destroy="shred -u -z -n 6"
 alias encrypt="gpg --symmetric --cipher-algo AES256"
 alias decrypt="gpg --decrypt"
+alias copy="rsync -avzh --progress"
+
+#  List all available comands (built-in, installed, and aliases & functions)
+alias lsall="compgen -c"
+
+# FUNCTION TO FIND LOCAL IP ADDRRESS
+
+local-ip() {
+  case "$(uname -s)" in
+    Linux*)
+      # Linux
+      ip addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -n 1
+      ;;
+    Darwin*)
+      # macOS
+      ipconfig getifaddr en0
+      ;;
+    *)
+      echo "Unsupported operating system"
+      return 1
+      ;;
+  esac
+}
+
+# FUNCTION TO FIND ALL PICTURES IN THE GIVEN DIR
+
+lsp() {
+    local dir=${1:-$(pwd)}
+
+    if [ -d "$dir" ]; then
+        fd -t f -e jpeg -e jpg -e png -e heic -i --base-directory "$dir"
+    else
+        echo "Error: The specified directory does not exist."
+    fi
+}
+
+
+# LINUX AND DARWIN SPESCIFIC ALIASES  
+
+case "$(uname -s)" in
+  Linux*)
+    alias fums="sudo apt autoclean && sudo apt clean && sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y --purge && sudo snap refresh"
+    alias up="sudo apt update && sudo apt upgrade -y && sudo apt autopurge -y"
+    alias install-date="/bin/ls -alct /|tail -1|awk '{print \$6, \$7, \$8}'"
+    alias scrot="scrot -q 100"
+    alias s="scrot -q 100"
+    alias s1="scrot -q 100 -d 1"
+    alias s3="scrot -q 100 -d 3"
+    alias ld='find -maxdepth 1 -type d -exec basename {} \;'
+    alias lA="/bin/ls -lA"
+    alias shutdown="shutdown -P now"
+    alias copy="xclip -i -selection clipboard"
+    alias paste="xclip -o -selecton clipboard"
+    alias cat='batcat'
+    alias dir='dir --color=auto'
+    alias vdir='vdir --color=auto'
+    alias destroy="shred -u -z -n 6"
+    alias get-chrome='wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
+    alias show-wifi-password="nmcli device wifi show-password"
+    
+
+    ;;
+  Darwin*)
+    alias battery="pmset -g batt"
+    alias sysinfo="system_profiler SPHardwareDataType SPSoftwareDataType"
+    alias vnstat="vnstat -i en0"
+    alias cat="bat"
+    # Show hidden files in Finder
+    alias showhidden='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
+    # Hide hidden files in Finder
+    alias hidehidden='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
+    # Empty the Trash
+    alias emptytrash='sudo rm -rf ~/.Trash/*'
+    # Turn off Wi-Fi
+    alias wifi-off='networksetup -setairportpower en0 off'
+    # Turn on Wi-Fi
+    alias wifi-on='networksetup -setairportpower en0 on'
+    # Install coreutils using brew to use shred
+    alias shred="gshred"
+    alias destroy="gshred -uzn 6"
+
+
+    ;;
+  esac
